language: c # change this to objective-c to test on a mac machine
sudo: required
env:
  global:
    - HAXE_VER=3.2.1
  matrix:
    - TARGET=neko
    - TARGET=cpp
    - TARGET=java
    - TARGET=cs
    - TARGET=python
    - TARGET=swf
    - TARGET=js TOOLCHAIN=default
    #- TARGET=js TOOLCHAIN=browser
    #- TARGET=php

matrix:
  fast_finish: true
  allow_failures:
    - env: SOME_ENV_HERE=some_opt

before_install:
  - travis_retry git clone --depth=50 --branch=master git://github.com/waneck/travis-hx.git ~/travis-hx

install:
  - ~/travis-hx/setup.sh
  - travis_retry haxelib remove hxcpp && haxelib install hxcpp || echo
  - travis_retry haxelib install hunit
  - travis_retry mkdir empty
  - travis_retry haxelib dev stablexui-core empty
  - travis_retry git clone https://github.com/StablexUI/Tests
  - travis_retry haxelib dev stablexui-tests Tests
  - travis_retry haxelib list stablexui-tests
  - travis_retry git clone https://github.com/StablexUI/Dummy.git
  - travis_retry haxelib dev stablexui-dummy Dummy

script:
  - cd $TRAVIS_BUILD_DIR
  - HXFLAGS="-cp src -lib stablexui-dummy -lib stablexui-tests -main StablexUITests -D HXCPP_STACK_TRACE" ~/travis-hx/build.sh
  - ~/travis-hx/runtests.sh $FILENAME # this will set the $FILENAME defined on the environment variable to run the tests