package sx.themes.flatui;

import sx.themes.FlatUITheme;
import sx.widgets.Text;


/**
 * Icons factory
 *
 */
class Icons
{
    /** Unicodes for glyphs in icons font */
    static public inline var GLYPH_EXIT              = 0xe000;
    static public inline var GLYPH_ENTRANCE          = 0xe001;
    static public inline var GLYPH_REDO              = 0xe002;
    static public inline var GLYPH_UNDO              = 0xe003;
    static public inline var GLYPH_ALIGN_CENTER      = 0xe004;
    static public inline var GLYPH_ALIGN_LEFT        = 0xe005;
    static public inline var GLYPH_ALIGN_RIGHT       = 0xe006;
    static public inline var GLYPH_PHOTO_SHUTTER     = 0xe007;
    static public inline var GLYPH_ARROW_DOWN        = 0xe008;
    static public inline var GLYPH_DOWN              = 0xe009;
    static public inline var GLYPH_LEFT              = 0xe00A;
    static public inline var GLYPH_RIGHT             = 0xe00B;
    static public inline var GLYPH_UP                = 0xe00C;
    static public inline var GLYPH_ARROW_LEFT        = 0xe00D;
    static public inline var GLYPH_ARROW_RIGHT       = 0xe00E;
    static public inline var GLYPH_THICK_ARROW_DOWN  = 0xe00F;
    static public inline var GLYPH_THICK_ARROW_LEFT  = 0xe010;
    static public inline var GLYPH_THICK_ARROW_RIGHT = 0xe011;
    static public inline var GLYPH_THICK_ARROW_UP    = 0xe012;
    static public inline var GLYPH_ARROW_UP          = 0xe013;
    static public inline var GLYPH_SOUND_WAVE        = 0xe014;
    static public inline var GLYPH_ECHO              = 0xe015;
    static public inline var GLYPH_MEDAL             = 0xe016;
    static public inline var GLYPH_BAN_SIGN          = 0xe017;
    static public inline var GLYPH_CHART_COLUMNS     = 0xe018;
    static public inline var GLYPH_COTTAGE           = 0xe019;
    static public inline var GLYPH_BATTERY_LOW       = 0xe01A;
    static public inline var GLYPH_BATTERY_FULL      = 0xe01B;
    static public inline var GLYPH_FLASK             = 0xe01C;
    static public inline var GLYPH_BELL              = 0xe01D;
    static public inline var GLYPH_BLUETOOTH         = 0xe01E;
    static public inline var GLYPH_BOLD              = 0xe01F;
    static public inline var GLYPH_BOLT              = 0xe020;
    static public inline var GLYPH_BOOKMARK          = 0xe021;
    static public inline var GLYPH_BANNER            = 0xe022;
    static public inline var GLYPH_CONTAINER         = 0xe023;
    static public inline var GLYPH_MONEY_POUND       = 0xe025;
    static public inline var GLYPH_WINFORM           = 0xe026;
    static public inline var GLYPH_BRUSH             = 0xe027;
    static public inline var GLYPH_BUG               = 0xe028;
    static public inline var GLYPH_MEGAPHONE         = 0xe029;
    static public inline var GLYPH_CALCULATOR        = 0xe02A;
    static public inline var GLYPH_CALCULATOR2       = 0xe02B;
    static public inline var GLYPH_CAMERA            = 0xe02C;
    static public inline var GLYPH_TRIANGLE_DOWN     = 0xe02D;
    static public inline var GLYPH_TRIANGLE_LEFT     = 0xe02E;
    static public inline var GLYPH_TRIANGLE_RIGHT    = 0xe02F;
    static public inline var GLYPH_TRIANGLE_UP       = 0xe030;
    static public inline var GLYPH_SHOPPING_TROLLEY  = 0xe031;
    static public inline var GLYPH_DIALOG_BALOONS    = 0xe032;
    static public inline var GLYPH_CHECK             = 0xe033;
    static public inline var GLYPH_ANGLE_DOWN        = 0xe034;
    static public inline var GLYPH_ANGLE_LEFT        = 0xe035;
    static public inline var GLYPH_ANGLE_RIGHT       = 0xe036;
    static public inline var GLYPH_ANGLE_UP          = 0xe037;
    static public inline var GLYPH_CHECK_ENCLOSED    = 0xe038;
    static public inline var GLYPH_CANCEL_ENCLOSED   = 0xe039;
    static public inline var GLYPH_CLIPBOARD         = 0xe03A;
    static public inline var GLYPH_CLOCK             = 0xe03B;
    static public inline var GLYPH_CLOUD_DOWN        = 0xe03C;
    static public inline var GLYPH_CLOUD_UP          = 0xe03D;
    static public inline var GLYPH_CLOUD             = 0xe03E;
    static public inline var GLYPH_CLOUDS            = 0xe03F;
    static public inline var GLYPH_TAG               = 0xe040;
    static public inline var GLYPH_GEAR              = 0xe041;
    static public inline var GLYPH_COMMAND_KEY       = 0xe046;
    static public inline var GLYPH_DIALOG_BALOON     = 0xe047;
    static public inline var GLYPH_COMPASS           = 0xe048;
    static public inline var GLYPH_CONTRAST          = 0xe049;
    static public inline var GLYPH_PARAGRAPHS        = 0xe04A;
    static public inline var GLYPH_CANCEL_LABEL      = 0xe050;
    static public inline var GLYPH_TEXT_SHEET        = 0xe052;
    static public inline var GLYPH_MONEY_DOLLAR      = 0xe053;
    static public inline var GLYPH_QUOTE_BEGIN       = 0xe056;
    static public inline var GLYPH_QUOTE_END         = 0xe057;
    static public inline var GLYPH_WATER_DROP        = 0xe058;
    static public inline var GLYPH_EJECT             = 0xe059;
    static public inline var GLYPH_LETTER            = 0xe05C;
    static public inline var GLYPH_OPEN_LETTER       = 0xe05D;
    static public inline var GLYPH_MONEY_EURO        = 0xe05E;
    static public inline var GLYPH_EYE               = 0xe065;
    static public inline var GLYPH_BLANK_SHEET       = 0xe067;
    static public inline var GLYPH_FIRE              = 0xe068;
    static public inline var GLYPH_FLAG              = 0xe069;
    static public inline var GLYPH_BOLD2             = 0xe06A;
    static public inline var GLYPH_FOLDER            = 0xe06B;
    static public inline var GLYPH_EARTH             = 0xe06F;
    static public inline var GLYPH_CHART_LINE        = 0xe070;
    static public inline var GLYPH_GRID_SMALL        = 0xe071;
    static public inline var GLYPH_GRID_MEDIUM       = 0xe072;
    static public inline var GLYPH_GRID_LARGE        = 0xe073;
    static public inline var GLYPH_HEADPHONES        = 0xe076;
    static public inline var GLYPH_HEART             = 0xe077;
    static public inline var GLYPH_HOUSE             = 0xe078;
    static public inline var GLYPH_INFINITY          = 0xe07B;
    static public inline var GLYPH_INFO              = 0xe07C;
    static public inline var GLYPH_ITALIC            = 0xe07D;
    static public inline var GLYPH_KEY               = 0xe081;
    static public inline var GLYPH_BROKEN_LINK       = 0xe085;
    static public inline var GLYPH_LINK              = 0xe086;
    static public inline var GLYPH_NAVIGATOR         = 0xe089;
    static public inline var GLYPH_LOCKED            = 0xe08A;
    static public inline var GLYPH_UNLOCKED          = 0xe08B;
    static public inline var GLYPH_REFRESH           = 0xe08C;
    static public inline var GLYPH_SEARCH            = 0xe08F;
    static public inline var GLYPH_MAP_LABEL         = 0xe090;
    static public inline var GLYPH_PAUSE             = 0xe092;
    static public inline var GLYPH_PLAY              = 0xe093;
    static public inline var GLYPH_RECORD            = 0xe094;
    static public inline var GLYPH_REWIND            = 0xe095;
    static public inline var GLYPH_FORWARD           = 0xe096;
    static public inline var GLYPH_PREVIOUS_TRACK    = 0xe097;
    static public inline var GLYPH_NEXT_TRACK        = 0xe098;
    static public inline var GLYPH_STOP              = 0xe099;
    static public inline var GLYPH_MICROPHONE        = 0xe09A;
    static public inline var GLYPH_MONITOR           = 0xe09E;
    static public inline var GLYPH_MOON              = 0xe09F;
    static public inline var GLYPH_MOVE              = 0xe0A0;
    static public inline var GLYPH_MELODY            = 0xe0A1;
    static public inline var GLYPH_CLIP              = 0xe0A2;
    static public inline var GLYPH_PENCIL            = 0xe0A3;
    static public inline var GLYPH_USERS             = 0xe0A4;
    static public inline var GLYPH_PERSON            = 0xe0A5;
    static public inline var GLYPH_SMARTPHONE        = 0xe0A6;
    static public inline var GLYPH_CHART_PIE         = 0xe0A7;
    static public inline var GLYPH_PIN               = 0xe0A8;
    static public inline var GLYPH_PLAY_ENCLOSED     = 0xe0A9;
    static public inline var GLYPH_PLUS              = 0xe0AA;
    static public inline var GLYPH_POWER             = 0xe0AB;
    static public inline var GLYPH_PRINTER           = 0xe0AC;
    static public inline var GLYPH_HEARTBEAT         = 0xe0AE;
    static public inline var GLYPH_PUZZLE            = 0xe0AF;
    static public inline var GLYPH_QUESTION          = 0xe0B0;
    static public inline var GLYPH_RAIN              = 0xe0B1;
    static public inline var GLYPH_SHUFFLE           = 0xe0B2;
    static public inline var GLYPH_REPEAT            = 0xe0B3;
    static public inline var GLYPH_RESIZE_DIAGONAL   = 0xe0B4;
    static public inline var GLYPH_RESIZE_VERTICAL   = 0xe0B5;
    static public inline var GLYPH_RESIZE_HORIZONTAL = 0xe0B6;
    static public inline var GLYPH_SIGNAL            = 0xe0B7;
    static public inline var GLYPH_SIGNAL2           = 0xe0B8;
    static public inline var GLYPH_SCROLL            = 0xe0B9;
    static public inline var GLYPH_SHIELD            = 0xe0BC;
    static public inline var GLYPH_VOLUME            = 0xe0BD;
    static public inline var GLYPH_ROAD_SIGN         = 0xe0BE;
    static public inline var GLYPH_BULLET_LIST       = 0xe0C1;
    static public inline var GLYPH_STAR              = 0xe0C2;
    static public inline var GLYPH_BRIGHTNESS        = 0xe0C3;
    static public inline var GLYPH_TABLET            = 0xe0C4;
    static public inline var GLYPH_LABEL             = 0xe0C5;
    static public inline var GLYPH_LABELS            = 0xe0C6;
    static public inline var GLYPH_TARGET            = 0xe0C7;
    static public inline var GLYPH_CHECK2            = 0xe0C8;
    static public inline var GLYPH_COMMAND_LINE      = 0xe0C9;
    static public inline var GLYPH_FONT              = 0xe0CA;
    static public inline var GLYPH_THUMB_DOWN        = 0xe0CB;
    static public inline var GLYPH_THUMB_UP          = 0xe0CC;
    static public inline var GLYPH_TIMER             = 0xe0CD;
    static public inline var GLYPH_TRASH             = 0xe0CF;
    static public inline var GLYPH_UNDERLINE         = 0xe0D0;
    static public inline var GLYPH_VOLUME_UP         = 0xe0D5;
    static public inline var GLYPH_VOLUME_DOWN       = 0xe0D6;
    static public inline var GLYPH_MUTE              = 0xe0D7;
    static public inline var GLYPH_ALERT             = 0xe0D8;
    static public inline var GLYPH_WIFI              = 0xe0D9;
    static public inline var GLYPH_WRENCH            = 0xe0DA;
    static public inline var GLYPH_CANCEL            = 0xe0DB;
    static public inline var GLYPH_MONEY_YEN         = 0xe0DC;
    static public inline var GLYPH_ZOOM_IN           = 0xe0DD;
    static public inline var GLYPH_ZOOM_OUT          = 0xe0DE;
    static public inline var GLYPH_RADIO_OFF         = 0xe0DF;
    static public inline var GLYPH_RADIO_ON          = 0xe0E0;

    /**
     * Creats an icon widget with specified glyph
     *
     * @param   size       Glyph size in DIPs. By default uses `FlatUITheme.FONT_SIZE`
     * @param   color      Glyph color. By default: `FlatUITheme.FONT_COLOR_LIGHT`
     */
    static public function exit (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_EXIT, size, color);
    static public function entrance (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ENTRANCE, size, color);
    static public function redo (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_REDO, size, color);
    static public function undo (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_UNDO, size, color);
    static public function aligncenter (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ALIGN_CENTER, size, color);
    static public function alignLeft (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ALIGN_LEFT, size, color);
    static public function alignRight (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ALIGN_RIGHT, size, color);
    static public function photoShutter (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_PHOTO_SHUTTER, size, color);
    static public function arrowDown (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ARROW_DOWN, size, color);
    static public function down (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_DOWN, size, color);
    static public function left (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_LEFT, size, color);
    static public function right (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_RIGHT, size, color);
    static public function up (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_UP, size, color);
    static public function arrowLeft (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ARROW_LEFT, size, color);
    static public function arrowRight (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ARROW_RIGHT, size, color);
    static public function thickArrowDown (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_THICK_ARROW_DOWN, size, color);
    static public function thickArrowLeft (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_THICK_ARROW_LEFT, size, color);
    static public function thickArrowRight (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_THICK_ARROW_RIGHT, size, color);
    static public function thickArrowUp (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_THICK_ARROW_UP, size, color);
    static public function arrowUp (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ARROW_UP, size, color);
    static public function soundWave (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_SOUND_WAVE, size, color);
    static public function echo (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ECHO, size, color);
    static public function medal (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MEDAL, size, color);
    static public function banSign (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BAN_SIGN, size, color);
    static public function chartColumns (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CHART_COLUMNS, size, color);
    static public function cottage (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_COTTAGE, size, color);
    static public function batteryLow (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BATTERY_LOW, size, color);
    static public function batteryFull (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BATTERY_FULL, size, color);
    static public function flask (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_FLASK, size, color);
    static public function bell (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BELL, size, color);
    static public function bluetooth (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BLUETOOTH, size, color);
    static public function bold (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BOLD, size, color);
    static public function bolt (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BOLT, size, color);
    static public function bookmark (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BOOKMARK, size, color);
    static public function banner (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BANNER, size, color);
    static public function container (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CONTAINER, size, color);
    static public function moneyPound (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MONEY_POUND, size, color);
    static public function winform (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_WINFORM, size, color);
    static public function brush (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BRUSH, size, color);
    static public function bug (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BUG, size, color);
    static public function megaphone (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MEGAPHONE, size, color);
    static public function calculator (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CALCULATOR, size, color);
    static public function calculator2 (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CALCULATOR2, size, color);
    static public function camera (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CAMERA, size, color);
    static public function triangleDown (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_TRIANGLE_DOWN, size, color);
    static public function triangleLeft (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_TRIANGLE_LEFT, size, color);
    static public function triangleRight (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_TRIANGLE_RIGHT, size, color);
    static public function triangleUp (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_TRIANGLE_UP, size, color);
    static public function shoppingTrolley (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_SHOPPING_TROLLEY, size, color);
    static public function dialogBaloons (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_DIALOG_BALOONS, size, color);
    static public function check (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CHECK, size, color);
    static public function angleDown (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ANGLE_DOWN, size, color);
    static public function angleLeft (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ANGLE_LEFT, size, color);
    static public function angleRight (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ANGLE_RIGHT, size, color);
    static public function angleUp (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ANGLE_UP, size, color);
    static public function checkEnclosed (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CHECK_ENCLOSED, size, color);
    static public function cancelEnclosed (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CANCEL_ENCLOSED, size, color);
    static public function clipboard (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CLIPBOARD, size, color);
    static public function clock (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CLOCK, size, color);
    static public function cloudDown (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CLOUD_DOWN, size, color);
    static public function cloudUp (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CLOUD_UP, size, color);
    static public function cloud (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CLOUD, size, color);
    static public function clouds (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CLOUDS, size, color);
    static public function tag (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_TAG, size, color);
    static public function gear (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_GEAR, size, color);
    static public function commandKey (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_COMMAND_KEY, size, color);
    static public function dialogBaloon (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_DIALOG_BALOON, size, color);
    static public function compass (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_COMPASS, size, color);
    static public function contrast (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CONTRAST, size, color);
    static public function paragraphs (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_PARAGRAPHS, size, color);
    static public function cancelLabel (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CANCEL_LABEL, size, color);
    static public function textSheet (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_TEXT_SHEET, size, color);
    static public function moneyDollar (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MONEY_DOLLAR, size, color);
    static public function quoteBegin (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_QUOTE_BEGIN, size, color);
    static public function quoteEnd (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_QUOTE_END, size, color);
    static public function waterDrop (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_WATER_DROP, size, color);
    static public function eject (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_EJECT, size, color);
    static public function letter (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_LETTER, size, color);
    static public function openLetter (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_OPEN_LETTER, size, color);
    static public function moneyEuro (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MONEY_EURO, size, color);
    static public function eye (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_EYE, size, color);
    static public function blankSheet (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BLANK_SHEET, size, color);
    static public function fire (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_FIRE, size, color);
    static public function flag (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_FLAG, size, color);
    static public function bold2 (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BOLD2, size, color);
    static public function folder (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_FOLDER, size, color);
    static public function earth (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_EARTH, size, color);
    static public function chartLine (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CHART_LINE, size, color);
    static public function gridSmall (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_GRID_SMALL, size, color);
    static public function gridMedium (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_GRID_MEDIUM, size, color);
    static public function gridLarge (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_GRID_LARGE, size, color);
    static public function headphones (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_HEADPHONES, size, color);
    static public function heart (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_HEART, size, color);
    static public function house (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_HOUSE, size, color);
    static public function infinity (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_INFINITY, size, color);
    static public function info (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_INFO, size, color);
    static public function italic (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ITALIC, size, color);
    static public function key (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_KEY, size, color);
    static public function brokenLink (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BROKEN_LINK, size, color);
    static public function link (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_LINK, size, color);
    static public function navigator (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_NAVIGATOR, size, color);
    static public function locked (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_LOCKED, size, color);
    static public function unlocked (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_UNLOCKED, size, color);
    static public function refresh (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_REFRESH, size, color);
    static public function search (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_SEARCH, size, color);
    static public function mapLabel (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MAP_LABEL, size, color);
    static public function pause (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_PAUSE, size, color);
    static public function play (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_PLAY, size, color);
    static public function record (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_RECORD, size, color);
    static public function rewind (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_REWIND, size, color);
    static public function forward (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_FORWARD, size, color);
    static public function previousTrack (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_PREVIOUS_TRACK, size, color);
    static public function nextTrack (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_NEXT_TRACK, size, color);
    static public function stop (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_STOP, size, color);
    static public function microphone (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MICROPHONE, size, color);
    static public function monitor (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MONITOR, size, color);
    static public function moon (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MOON, size, color);
    static public function move (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MOVE, size, color);
    static public function melody (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MELODY, size, color);
    static public function clip (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CLIP, size, color);
    static public function pencil (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_PENCIL, size, color);
    static public function users (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_USERS, size, color);
    static public function person (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_PERSON, size, color);
    static public function smartphone (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_SMARTPHONE, size, color);
    static public function chartPie (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CHART_PIE, size, color);
    static public function pin (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_PIN, size, color);
    static public function playEnclosed (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_PLAY_ENCLOSED, size, color);
    static public function plus (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_PLUS, size, color);
    static public function power (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_POWER, size, color);
    static public function printer (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_PRINTER, size, color);
    static public function heartbeat (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_HEARTBEAT, size, color);
    static public function puzzle (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_PUZZLE, size, color);
    static public function question (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_QUESTION, size, color);
    static public function rain (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_RAIN, size, color);
    static public function shuffle (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_SHUFFLE, size, color);
    static public function repeat (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_REPEAT, size, color);
    static public function resizeDiagonal (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_RESIZE_DIAGONAL, size, color);
    static public function resizeVertical (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_RESIZE_VERTICAL, size, color);
    static public function resizeHorizontal (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_RESIZE_HORIZONTAL, size, color);
    static public function signal (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_SIGNAL, size, color);
    static public function signal2 (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_SIGNAL2, size, color);
    static public function scroll (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_SCROLL, size, color);
    static public function shield (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_SHIELD, size, color);
    static public function volume (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_VOLUME, size, color);
    static public function roadSign (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ROAD_SIGN, size, color);
    static public function bulletList (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BULLET_LIST, size, color);
    static public function star (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_STAR, size, color);
    static public function brightness (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_BRIGHTNESS, size, color);
    static public function tablet (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_TABLET, size, color);
    static public function label (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_LABEL, size, color);
    static public function labels (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_LABELS, size, color);
    static public function target (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_TARGET, size, color);
    static public function check2 (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CHECK2, size, color);
    static public function commandLine (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_COMMAND_LINE, size, color);
    static public function font (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_FONT, size, color);
    static public function thumbDown (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_THUMB_DOWN, size, color);
    static public function thumbUp (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_THUMB_UP, size, color);
    static public function timer (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_TIMER, size, color);
    static public function trash (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_TRASH, size, color);
    static public function underline (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_UNDERLINE, size, color);
    static public function volumeUp (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_VOLUME_UP, size, color);
    static public function volumeDown (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_VOLUME_DOWN, size, color);
    static public function mute (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MUTE, size, color);
    static public function alert (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ALERT, size, color);
    static public function wifi (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_WIFI, size, color);
    static public function wrench (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_WRENCH, size, color);
    static public function cancel (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_CANCEL, size, color);
    static public function moneyYen (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_MONEY_YEN, size, color);
    static public function zoomIn (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ZOOM_IN, size, color);
    static public function zoomOut (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_ZOOM_OUT, size, color);
    static public function radioOff (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_RADIO_OFF, size, color);
    static public function radioOn (size:Int = -1, color:Int = -1) return FlatUITheme.icon(GLYPH_RADIO_ON, size, color);


}//class Icons